services:
  db:
    image: postgres
    container_name: activitytracker-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: activitytracker-keycloak
    command: start-dev --import-realm
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KEYCLOAK_ADMIN_USER}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    ports:
      - "8081:8080"
    volumes:
      - ./keycloak-config:/opt/keycloak/data/import
    depends_on:
      - db

  backend:
    build: .
    image: ghcr.io/hse-classes/ss26-aktivitatstracker:latest
    container_name: activitytracker-backend
    ports:
      - "8443:8443"
    volumes:
      - /root/keystore.p12:/app/keystore.p12
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      KEYCLOAK_SERVERURL: http://keycloak:8080
      KEYCLOAK_ADMIN_USER: ${KEYCLOAK_ADMIN_USER}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      WEATHERAPI_KEY: ${weatherapi_key}
      WEATHERAPI_CITY: ${weatherapi_city}
    depends_on:
      - db
      - keycloak