services:
  db:
    image: postgres
    container_name: activitytracker-db
    environment:
      POSTGRES_DB: activitytracker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"