spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:5432/activitytracker
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

weatherapi_key=${weatherapi_key}
weatherapi_city=${weatherapi_city}
keycloak.serverUrl=http://localhost:8081
keycloak.realm=ActivityTracker
keycloak.adminRealm=master
keycloak.clientId=admin-cli
keycloak.adminUser=${KEYCLOAK_ADMIN_USER}
keycloak.adminPassword=${KEYCLOAK_ADMIN_PASSWORD}
